spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 

token:
  expiration_time: 764000000
  secret: MY_SECRET_20230511_PROD
gateway:
  ip: 192.168.0.76
