spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQB3Wnw081rrwh/U70YAr/6HFnkbm28Tbt0gmkv8CJT7nur0TOAYXStAY2q+TIe27VE4iubEi4QgwuptCW14nHcIO/3RrcVtYqEYgQct8f6+JPgM2R6DDfEXHt+XhzHkI9PKTxEfx/D+zwMGsOz6Y7nkfNfMo6fcNnhlPpwPWAC42osRaHk59Wl95MPHlib2D+tp3WLh5HypnX4se5Pz/wo7bwXF8VQ97WujHGpGJlqZ7Ll/gAj/B5n02Uzxik1lK3annrij2lV8YYiOI7+hJKFWfSQTabCbhLqgT5RXen9cqUbs4uo6ZR5ForHv9Jap7ilEr1G2RYFoyF7TUuWZIkCwCOx9bXW7CdkjpWz3vQypn8coclctGiD7QwECwgbAr1g='

token:
  expiration_time: 764000000
  secret: MY_SECRET_20230511_PROD
gateway:
  ip: 192.168.0.76

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders